CREATE TABLE IF NOT EXISTS urls (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    original VARCHAR(255) NOT NULL,
    short VARCHAR(255) NOT NULL UNIQUE,
    short_path VARCHAR(255) NOT NULL UNIQUE
);